- name: Gather and Report z/OS Facts for Chatbot
  hosts: zos_host
  gather_facts: false
  # Assuming environment_vars are defined elsewhere (e.g., AAP Job Template)
  environment: "{{ environment_vars }}"
  tasks:

    - name: Gather z/OS host facts
      ibm.ibm_zos_core.zos_gather_facts:
      # Make this task less noisy if using yaml/minimal callback
      tags: always # Ensure it always runs

    - name: Report Master Catalog Information
      ansible.builtin.debug:
        msg: | # Use YAML block scalar for cleaner multi-line message definition
          Master Catalog DSN: {{ ansible_facts.master_catalog_dsn }}
          Master Catalog Volser: {{ ansible_facts.master_catalog_volser }}
      tags: facts, catalog # Add tags for potential selective running

    - name: Report CPC and IODF Information
      ansible.builtin.debug:
        msg: | # Use YAML block scalar
          Manufacturer: {{ ansible_facts.cpc_nd_manufacturer }}
          Model: {{ ansible_facts.cpc_nd_model }}
          Plant: {{ ansible_facts.cpc_nd_plant }}
          IODF Name: {{ ansible_facts.iodf_name }}
          IODF Config: {{ ansible_facts.iodf_config }}
      tags: facts, hardware, iodf # Add tags

    - name: Provide System Summary
      ansible.builtin.debug:
        msg: | # Use YAML block scalar
          System Summary for {{ ansible_facts.sys_name }}:
          Product: {{ ansible_facts.product_name }} {{ ansible_facts.product_version }}.{{ ansible_facts.product_release }}.{{ ansible_facts.product_mod_level }}
          Sysplex: {{ ansible_facts.sysplex_name }}
          Primary JES: {{ ansible_facts.primary_jes }}
          IPL Volume: {{ ansible_facts.ipl_volume }}
          Master Catalog: {{ ansible_facts.master_catalog_dsn }} on {{ ansible_facts.master_catalog_volser }}
          Hardware: {{ ansible_facts.cpc_nd_manufacturer }} {{ ansible_facts.cpc_nd_type }} (Model: {{ ansible_facts.cpc_nd_model }})
      tags: facts, summary # Add tags