---
- name: Gather z/OS-specific facts.
  hosts: zos_host
  gather_facts: false
  environment:
    "{{ environment_vars }}"
  tasks:
    - name: Gather all facts about z/OS host.
      ibm.ibm_zos_core.zos_gather_facts:

    - name: Print gathered facts about the master catalog.
      ansible.builtin.debug:
        msg: |
          +------------------------+-------------------+
          | Master Catalog DSN     | {{ ansible_facts.master_catalog_dsn }} |
          | Master Catalog Volser  | {{ ansible_facts.master_catalog_volser }} |
          +------------------------+-------------------+

    - name: Print only CPC and IODF info from gathered z/OS facts.
      ansible.builtin.debug:
        msg: |
          +---------------+----------------+-------------+--------------+----------------+
          | Manufacturer  | Model         | Plant       | IODF Name    | IODF Config    |
          +---------------+----------------+-------------+--------------+----------------+
          | {{ cpc_nd_manufacturer }} | {{ cpc_nd_model }}   | {{ cpc_nd_plant }}  | {{ iodf_name }}      | {{ iodf_config }}     |
          +---------------+----------------+-------------+--------------+----------------+

    - name: Print out all gathered facts about the z/OS host.
      ansible.builtin.debug:
        var: ansible_facts