- name: Gather z/OS-specific facts and format output.
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  tasks:

    - name: Gather all facts about z/OS host.
      ibm.ibm_zos_core.zos_gather_facts:

    - name: Save gathered facts to a JSON file.
      copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: "/u/ibmuser/aap/zos_facts.json"

    - name: Run Python script to format output.
      script: /u/ibmuser/aap/format_zos_facts.py

    - name: Display formatted output.
      ansible.builtin.debug:
        msg: "{{ lookup('file', '/u/ibmuser/aap/zos_facts_formatted.txt') }}"
