- name: Gather and Format z/OS-specific Facts
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    # Define a list of interesting fact categories to highlight
    fact_categories:
      - title: System Information
        facts:
          - key: product_name
          - key: product_release
          - key: product_version
          - key: sysplex_name
          - key: sys_name
          - key: primary_jes

      - title: Hardware Details
        facts:
          - key: cpc_nd_manufacturer
          - key: cpc_nd_model
          - key: cpc_nd_plant
          - key: arch_level

      - title: Storage and Catalog
        facts:
          - key: master_catalog_dsn
          - key: master_catalog_volser
          - key: parmlib_dsn
          - key: parmlib_volser
          - key: ipl_volume

      - title: IODF Configuration
        facts:
          - key: iodf_name
          - key: iodf_config
          - key: iodf_unit_addr

  tasks:
    - name: Gather all facts about z/OS host
      ibm.ibm_zos_core.zos_gather_facts:

    - name: Format and Display z/OS Facts
      block:
        - name: Display Formatted Facts
          ansible.builtin.debug:
            msg: |
              ╔══════════════════════════════════════════════════════════
              ║ Z/OS HOST SYSTEM FACTS
              ╚══════════════════════════════════════════════════════════
              {% for category in fact_categories %}
              ► {{ category.title }}:
              {% for fact_item in category.facts %}
                - {{ fact_item.key }}: {{ ansible_facts[fact_item.key] | default('N/A') }}
              {% endfor %}

              {% endfor %}
              ╔══════════════════════════════════════════════════════════
              ║ ADDITIONAL TECHNICAL DETAILS
              ╚══════════════════════════════════════════════════════════
              - Full hostname: {{ inventory_hostname }}
              - Complete Fact Set: Refer to the detailed dump below

        - name: Provide Complete Fact Set
          ansible.builtin.debug:
            var: ansible_facts
            verbosity: 1  # This will only show with -v flag