- name: Gather z/OS-specific facts.
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  tasks:

    - name: Gather all facts about z/OS host.
      ibm.ibm_zos_core.zos_gather_facts:

    - name: Print gathered facts about the master catalog.
      ansible.builtin.debug:
        msg: |
          Master Catalog Information:
            - DSN: {{ ansible_facts.master_catalog_dsn }}
            - VOLSER: {{ ansible_facts.master_catalog_volser }}

    - name: Print only CPC and IODF info from gathered z/OS facts.
      ansible.builtin.debug:
        msg: |
          CPC & IODF Information:
            - Manufacturer: {{ ansible_facts.cpc_nd_manufacturer }}
            - Model: {{ ansible_facts.cpc_nd_model }}
            - Plant: {{ ansible_facts.cpc_nd_plant }}
            - IODF Name: {{ ansible_facts.iodf_name }}
            - IODF Config: {{ ansible_facts.iodf_config }}

    - name: Print all gathered facts about the z/OS host in YAML format.
      ansible.builtin.debug:
        msg: "{{ ansible_facts | to_nice_yaml }}"
