- name: Gather and display z/OS-specific facts (Human-Readable)
  hosts: zos_host
  gather_facts: false
  environment:
    # --- Add these locale settings ---
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
    # --------------------------------
    ANSIBLE_NOCOLOR: "1"
    # Merge with your original environment_vars if they exist
    # Example: "{{ environment_vars | combine({'LANG': 'en_US.UTF-8', 'LC_ALL': 'en_US.UTF-8', 'ANSIBLE_NOCOLOR': '1'}) }}"

  tasks:
    - name: Gather all facts about z/OS host.
      ibm.ibm_zos_core.zos_gather_facts:
      # Add environment here too, if needed at task level (usually play level is sufficient)
      # environment:
      #   LANG: "en_US.UTF-8"
      #   LC_ALL: "en_US.UTF-8"

    # ... rest of your tasks ...
    - name: Display gathered facts about the master catalog.
      ansible.builtin.debug:
        msg: |
          Master Catalog Information:
            Dataset Name: {{ ansible_facts.master_catalog_dsn | default('N/A') }}
            Volume Serial: {{ ansible_facts.master_catalog_volser | default('N/A') }}
      when: ansible_facts.master_catalog_dsn is defined

    - name: Display CPC and IODF info from gathered z/OS facts.
      ansible.builtin.debug:
        msg: |
          CPC and IODF Information:
            Manufacturer: {{ ansible_facts.cpc_nd_manufacturer | default('N/A') }}
            Model: {{ ansible_facts.cpc_nd_model | default('N/A') }}
            Plant: {{ ansible_facts.cpc_nd_plant | default('N/A') }}
            IODF Name: {{ ansible_facts.iodf_name | default('N/A') }}
            IODF Config: {{ ansible_facts.iodf_config | default('N/A') }}
      when: ansible_facts.cpc_nd_manufacturer is defined or ansible_facts.iodf_name is defined

    - name: Display all gathered facts about the z/OS host (YAML format).
      ansible.builtin.debug:
        msg: |
          All Gathered z/OS Facts:
          {{ ansible_facts | to_nice_yaml(indent=2) }}
      when: ansible_facts is defined